run _m10_nsub3_nsim10000
v tensor([[ 1.3660,  2.4514],
        [ 1.3570,  1.5559],
        [ 1.5796, -0.1466]], device='cuda:0')
sim {'image': tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0')}
sim['image'] min and max tensor(0., device='cuda:0') tensor(26.5118, device='cuda:0')
['x_1', 'y_1', 'x_2', 'y_2', 'x_3', 'y_3']
Traceback (most recent call last):
  File "/home/eliasd/lensing/pyrofit-lensing-analysis/experiments/swyft_subhalo_3/create_store.py", line 86, in <module>
    run()
  File "/home/eliasd/.pyenv/versions/lens-3.9.7/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/eliasd/.pyenv/versions/lens-3.9.7/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/eliasd/.pyenv/versions/lens-3.9.7/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/eliasd/.pyenv/versions/lens-3.9.7/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/eliasd/lensing/pyrofit-lensing-analysis/experiments/swyft_subhalo_3/create_store.py", line 77, in run
    store = swyft.DirectoryStore(path=SIM_PATH, simulator=simulator)
  File "/home/eliasd/lensing/swyft/swyft/store/store.py", line 520, in __init__
    super().__init__(
  File "/home/eliasd/lensing/swyft/swyft/store/store.py", line 87, in __init__
    raise KeyError(
KeyError: "The zarr storage is corrupted. It should either be empty or only have the keys ['samples', 'metadata']."
